<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" />
     <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="style.css">

    <title>Cadastro de Autómveis</title>
</head>
<body>
    <div class="container">

    <div class="container">

<div class="row">
        <div class="col-12 central pt-5">
            <h1 class="text-center">Cadastro de Automóvel</h1>
        </div>
    </div>

    <form method="post" action="/cadastroVeiculo/">
<div class="form-row">

<div class="form-group col-md-12">
  <label for="inputAddress">Modelo:</label>
  <input type="text" class="form-control" name="modelo" id="inputAddress" placeholder="Chevette">
</div>
<div class="form-group col-md-12">
  <label for="inputAddress">Marca:</label>
  <input type="text" class="form-control" name="marca" id="inputAddress" placeholder="Chevrolet">
</div>
<div class="form-group col-md-12">
  <label for="inputPassword4">Ano de fabricação</label>
  <input type="number" class="form-control" name="ano" id="inputPassword4" placeholder="1985">
</div>


</div>

<button type="submit" class="btn btn-dark">Cadastrar</button>
</form>
</div>
</body>
</html>