<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" />
     <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="style.css">

    <title>Editor de Autómveis</title>
</head>
<body>
    <div class="container">

    <div class="container">

<div class="row">
        <div class="col-12 central pt-5">
         

      <h1 class="text-center">Editar Veículo </h1>

            
        </div>
    </div>

    <form method="post" action="/veiculoEditado/">
<div class="form-row">

<?php
foreach ($carroEditar as $key => $value) {
  echo "<div class='form-group col-md-12'>";
  echo "<label for='inputAddress'>".'Identificador:'."</label>";
    echo "<input type='text' class='form-control' name='idcarro' value='" . $value['idcarro'] . "'>"; 
    echo "</div>";
    echo "<div class='form-group col-md-12'>";
    echo "<label for='inputAddress'>".'Modelo:'."</label>";
    echo "<input type='text' class='form-control'  name='modelo' value='" . $value['modelo'] . "'>"; 
    echo "</div>";
    echo "<div class='form-group col-md-12'>";
    echo "<label for='inputAddress'>".'Marca:'."</label>";
    echo "<input type='text' class='form-control'  name='marca' value='" . $value['marca'] . "'>"; 
    echo "</div>";
    echo "<div class='form-group col-md-12'>";
    echo "<label for='inputAddress'>".'Ano de fabricação:'."</label>";
    echo "<input type='number' class='form-control' step='any' min='1900' max='2019'  name='ano' value='" . $value['ano'] . "'>"; 
    echo "</div>";
   
}
?>
</div>

<button type="submit" class="btn btn-dark">Editar</button>
</form>
</div>
</body>
</html>
