<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" />
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="style.css">

  <title>Vender autómveis</title>
</head>

<body>
  <div class="container">

    <div class="container">

      <div class="row">
        <div class="col-12 central pt-5">


          <h1 class="text-center">Vender Veículo </h1>


        </div>
      </div>

      <form method="post" action="/veiculoVendido/">
        <div class="form-row">
          <button type="submit" class="btn btn-dark mx-auto">Vender</button>

          <div class='form-group col-md-12'>
            <label for="inputAddress">Selecione o carro:</label>
            <select class="form-control" id="exampleFormControlSelect1" name="idcarro">

              <?php
              foreach ($venderCarro as $key => $value) {
                echo "<option value='" . $value['idcarro'] . "'>" . $value['modelo'] . "</option>";
                echo "</div>";
              }
              ?>
</select>
          </div>
          <div class='form-group col-md-12'>

            <label for="inputAddress">Selecione o Comprador:</label>
            <select class="form-control" id="exampleFormControlSelect1" name="idcomprador">
              <?php
              foreach ($compradores as $key => $value) {
                echo "<option value='" . $value['idcomprador'] . "'>" . $value['nome'] . "</option>";
                echo "</div>";
              }
              ?>
            </select>
          </div>




      </form>
    </div>
</body>

</html>